"""
Generate a cohort of synthetic users with EMA, Heart rate, timestamp and unique uuid. 
- Generator can tweak response rate to simulate 'No Reponse' to EMAs 
- Current dataframe format is not suited to store in database!

Author: @tylerrleee
Date: 05/31/2026
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import matplotlib.dates as mdates
import uuid

### EMA GENERATOR 
def generate_user_ids(n_users):
    """Generates a list of n_users strings, each being a unique UUID"""
    return [str(uuid.uuid4()) for _ in range(n_users)]

def generate_user(user_id,
                  days,
                  ema_per_day,
                  rng,
                  resp_rate=0.80,
                  mean_gap_length = 3,
                  mu=None,
                  sigma=None,
                  rho=None):
    """

    Generate one user's EMA series with KNOWN latent volatility.
    Assumes sample is normally distributed

    mu / sigma / rho may be passed explicitly to assign a *known* latent
    volatility (used by the MSSD validation harness to build Stable vs.
    Volatile cohorts). When left as None they are drawn at random, preserving
    the original per-user behaviour.
    """

    n = days * ema_per_day

    # per-user latent parameters (ground truth for the population).
    # Drawn at random unless the caller pins them to a known value.
    if mu is None:
        mu = rng.uniform(2.0, 4.0)
    if sigma is None:
        sigma = rng.uniform(0.3, 1.5) # How volatile a person is (0 means they are exactly at the mean)
    if rho is None:
        rho = rng.uniform(0.1, 0.8) # personal correlation

    # AR(1)  -- consecutive points are related
    # lambda^2 = E[(x_{i+1} - x_i)^2] = 2\sigma^2(1-p(1))
    

    z = np.zeros(n)
    z[0] = rng.normal(0, sigma) # define mean, and std (degree of spread)
    for t in range(1, n):
      z[t] = rho * z[t-1] + rng.normal(0, sigma * np.sqrt(1 - rho**2))
    latent = mu + z

    # map latent to Likert response
    ema = np.clip(np.round(latent), 1, 5)
  
    mask = _clustered_missing_mask(n, resp_rate, mean_gap_length, rng) # bool mask
    ema[mask] = np.nan
    
    expected_mssd = 2.0 * sigma**2 * (1 - rho) # ground truth
    timestamps = pd.date_range(start="2026-06-01", periods=n, freq="min")

    return pd.DataFrame({
        "user_id": user_id,
        "timestamp": timestamps,
        "prompt_idx": np.arange(n),
        "day": np.arange(n) // ema_per_day,
        "ema": ema,
        "true_sigma": sigma,
        "true_rho": rho,
        "true_expected_mssd": expected_mssd,
    })

  
def _clustered_missing_mask(n, resp_rate, mean_gap_length, rng):
    """
    Boolean mask of length n where True = missing (NaN), generated by a
    two-state Markov chain so that missingness arrives in clusters.

    resp_rate        : fraction of prompts answered (missing rate m = 1 - resp_rate)
    mean_gap_length  : average length of a missing run, in prompts (>= 1)
    rng              : np.random.Generator

    The long-run missing rate is m regardless of clustering; mean_gap_length
    only controls how the misses are clumped.
    """

    missing_rate = 1.0 - resp_rate

    if missing_rate <= 0.0:
      return np.zeros(n, dtype=bool) # nobody miss answering
    
    elif missing_rate >= 1.0:
      return np.ones(n, dtype=bool) # everything misses
    
    if mean_gap_length < 1.0:
      raise ValueError("mean_gap_length must be >= 1")
    
    # transition probabilities
    b = 1.0 / mean_gap_length # P(missing -> responding): ending a gap
    a = missing_rate * b / (1.0 - missing_rate) # P(responding -> missing) [0,1] starts a gap

    # feasiability
    if a > 1.0:
        raise ValueError(
            f"infeasible combo: mean_gap_length {mean_gap_length:.2f} with mean gap "
            f"{mean_gap_length} needs P(start gap) = {a:.2f} > 1. "
            f"lower the missing rate or allow longer gaps."
        )
    mask = np.zeros(n, dtype=bool)
    missing = rng.random() < missing_rate
    mask[0] = missing
    for t in range(1, n):
      if missing:
        missing = rng.random() >= b # stay missing
      
      else:
        missing = rng.random() < a # start a gap w/ P(responding -> missing)
      
      mask[t] = missing
    
    return mask
    
def generate_cohort(users = 100,
                    days  = 14,
                    ema_per_day = 5,
                    seed = 0,
                    resp_rate = 0.8,
                    mean_gap_length = 3,
                    user_ids = None,
                    mu = None,
                    sigma = None,
                    rho = None):

    if users < 1:
      raise ValueError(f"Need more than one user to generate... got {users}")
    if days < 1:
      raise ValueError(f"Need more than one day to generate... got {days}")
    if ema_per_day < 1:
      raise ValueError(f"Need more than one day to generate... got {ema_per_day}")
    if resp_rate > 1 or resp_rate < 0:
      raise ValueError(f"Need RESPONSE RATE within range [0,1]... got {resp_rate}")

    if user_ids is None:
      user_ids = generate_user_ids(users)
    rng = np.random.default_rng(seed)
    all_data = []

    for uid in user_ids:
        df_user = generate_user(user_id = uid,
                                days = days,
                                ema_per_day = ema_per_day,
                                rng = rng,
                                resp_rate = resp_rate,
                                mean_gap_length = mean_gap_length,
                                mu = mu,
                                sigma = sigma,
                                rho = rho)
        all_data.append(df_user)

    return pd.concat(all_data)

### WEARABLE PROFILE
# We simulate the Garmin hardware line (Venu 3 / Vivoactive 5/6) rather than
# Fitbit. Garmin derives stress from continuous HRV (RMSSD on inter-beat
# intervals) mapped to a 0-100 score, so each sample is flagged with its
# source device and carries an HRV value alongside heart rate.
GARMIN_DEVICES = ("Garmin Venu 3", "Garmin Vivoactive 5", "Garmin Vivoactive 6")


def _generate_hrv_and_stress(hr,
                             rng,
                             alpha = 55.0,
                             hrv_noise_std = 4.0,
                             rmssd_clip = (12.0, 120.0),
                             stress_window = (15.0, 90.0),
                             stress_noise_std = 4.0):
    """
    Derive minute-level HRV (RMSSD) and a Garmin-style stress score (0-100)
    from an existing heart-rate array.

    Physiology: a high heart rate compresses the inter-beat interval, leaving
    less room to vary, so HRV falls; resting states elevate HRV. We tie RMSSD
    inversely to HR:

        RMSSD_t = alpha * (100 / HR_t) + eps_t

    where `alpha` scales into a young-adult Garmin RMSSD range and `eps_t`
    is somatic noise. Garmin then maps continuous HRV to a 0-100 stress score:
    low HRV -> high stress. Because exercise bouts spike HR, they depress HRV
    and therefore raise stress, giving the algorithmic HR-spike -> stress
    correlation the spec calls for.

    Args:
        hr             : 1D array of minute-level heart rate (bpm).
        rng            : np.random.Generator.
        alpha          : RMSSD scaling factor (young-adult Garmin range).
        hrv_noise_std  : std of additive RMSSD noise (ms).
        rmssd_clip     : (lo, hi) physiological clamp for RMSSD (ms).
        stress_window  : (lo, hi) RMSSD band normalised onto the 0-100 score.
        stress_noise_std : std of additive stress noise (points).

    Returns:
        (rmssd, stress) float arrays, same length as `hr`.
    """
    hr = np.asarray(hr, dtype=float)
    n = hr.shape[0]

    # inverse HR -> HRV coupling
    rmssd = alpha * (100.0 / hr) + rng.normal(0, hrv_noise_std, n)
    rmssd = np.clip(rmssd, *rmssd_clip)

    # Garmin stress: normalise RMSSD over a fixed band, then invert so that
    # low HRV reads as high stress.
    lo, hi = stress_window
    norm = np.clip((rmssd - lo) / (hi - lo), 0.0, 1.0)
    stress = 100.0 * (1.0 - norm) + rng.normal(0, stress_noise_std, n)
    stress = np.clip(stress, 0.0, 100.0)

    return rmssd, stress


### HEART RATE GENERATOR
def _generate_heart_rate(user_id,
                        days,
                        rng,
                        resting_hr = None,
                        hr_range = (60, 100),
                        circadian_amp = 6.0,
                        noise_std = 2.0,
                        bouts_per_day = (0, 3),
                        bout_minutes = (20, 60),
                        bout_intensity = (15, 40),
                        source = "Garmin Venu 3"):
    """
      Minute-level synthetic heart rate for one user over `days` days.

      Args:
        resting_hr : per-user baseline (drawn if None, so users differ)
        circadian  : daily rhythm, lowest ~4am, highest ~4pm
        noise      : minute-to-minute white noise (see note on AR(1) below)
        bouts      : random activity spikes (count/time/length/size all vary)

      Returns long-format DataFrame: user_id, minute, day, hr.
    """

    # Build time-series
    min_per_day = 24 * 60
    n = days * min_per_day
    t = np.arange(n)

    # assuming our samples are just young adults
    # 18-24 years old
    # https://my.clevelandclinic.org/health/diagnostics/heart-rate
    if resting_hr is None:
        resting_hr = rng.uniform(*hr_range)
    
    minute_of_day = t % min_per_day
    circadian = -circadian_amp * np.cos(2*np.pi*(minute_of_day - 240) / min_per_day)

    noise = rng.normal(0, noise_std, n)

    activity = np.zeros(n)
    for day in range(days):
        for _ in range(rng.integers(bouts_per_day[0], bouts_per_day[1] + 1)):
            duration = int(rng.integers(*bout_minutes))
            start    = day * min_per_day + int(rng.integers(0, min_per_day - duration))
            activity[start: start + duration] += rng.uniform(*bout_intensity)

    hr = np.clip(resting_hr + circadian + noise + activity, 40, 200)

    # Garmin HRV + stress derived from the heart-rate trace
    rmssd, stress = _generate_hrv_and_stress(hr, rng)

    timestamps = pd.date_range(start="2026-06-01", periods=n, freq="min")
    return pd.DataFrame({
            "user_id":   user_id,
            "timestamp": timestamps,
            "minute":    t,
            "day":       t // min_per_day,
            "hr":        hr,
            "hrv_rmssd": rmssd,
            "stress":    stress,
            "source":    source,
        })

def generate_HR(users = 100,
                days  = 14,
                seed = 0,
                heart_rate = None,
                user_ids = None):

    if users < 1:
      raise ValueError(f"Need more than one user to generate... got {users}")
    if days < 1:
        raise ValueError(f"Need more than one day to generate... got {days}")

    if user_ids is None:
      user_ids = generate_user_ids(users)
    rng = np.random.default_rng(seed)

    # Generate data for all users and concatenate. Each user is assigned a
    # Garmin device model so the `source` flag varies across the cohort.
    all_data = []
    for uid in user_ids:
        source = GARMIN_DEVICES[rng.integers(0, len(GARMIN_DEVICES))]
        df_user = _generate_heart_rate(user_id=uid, days=days, rng=rng,
                                       resting_hr=heart_rate, source=source)
        all_data.append(df_user)

    return pd.concat(all_data, ignore_index = True)

