# Generated by Django 5.1.1 on 2026-06-12 03:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_jitailog"),
    ]

    operations = [
        migrations.AddField(
            model_name="ema",
            name="status",
            field=models.CharField(
                choices=[("answered", "Answered"), ("missed", "Missed")],
                default="answered",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="heartratesample",
            name="hrv_rmssd",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="heartratesample",
            name="source",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="heartratesample",
            name="zone",
            field=models.CharField(
                blank=True,
                choices=[
                    ("out_of_range", "Out of Range"),
                    ("fat_burn", "Fat Burn"),
                    ("cardio", "Cardio"),
                    ("peak", "Peak"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="StressSample",
            fields=[
                ("sample_id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField()),
                (
                    "stress_score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("source", models.CharField(blank=True, default="", max_length=64)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.wearabledevice",
                    ),
                ),
            ],
        ),
    ]
